version: "3.7"
services:
  app:
    container_name: app
    build:
      context: .
      dockerfile: Dockerfile
    env_file: .env
    volumes:
      - ./src:/app/src
    environment:
      - PORT=${APP_PORT}
    ports:
      - 3000:80
      - 5000:5000
    networks:
      - network_gem

  mongo:
    container_name: mongo
    image: mongo
    restart: always
    ports:
      - 27017:27017
    # environment:
    #   MONGO_INITDB_ROOT_USERNAME: root
    #   MONGO_INITDB_ROOT_PASSWORD: 123
    networks:
      - network_gem

volumes:
  elasticsearch:
    driver: local


networks:
  network_gem:
    driver: bridge