version: "3.7"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    command: npm run dev
    env_file: .env
    environment:
      - PORT=${APP_PORT}
    ports:
      - "3300:3300"
    volumes:
      - .:/user/app